- name: Report updates for Windows WMs
  hosts: all
  gather_facts: true
  tasks:
  - name: Remove old file, if present
    win_file:
      path: C:\test-script.ps1
      state: absent
  
  - name: Remove old file, if present
    win_file:
      path: C:\output-1.txt
      state: absent
    
  - name: Touch a file 
    win_file:
      path: C:\test-script.ps1
      state: touch
  
  - name: Add a line to a file 
    win_lineinfile:
      path: C:\test-script.ps1
      line: |
        $a=0
        $b=0
        $strComputer = "localhost"
        $a=Get-WmiObject Win32_OperatingSystem -ComputerName $strComputer | fl *freePhysical* | Out-String
        $b=Get-WmiObject Win32_OperatingSystem -ComputerName $strComputer | fl *totalvisiblememory* | Out-String
        $a = $a -replace '\D+(\d+)','$1'
        $b = $b -replace '\D+(\d+)','$1'
        $result = [math]::Round($a/$b*10000)/100
        Write-Output "Memory Usage: $result"

  - name: Execute a comand in the remote shell, stdout goes to the specified file on the remote
    win_shell: C:\test-script.ps1 >> C:\output-1.txt
    register: script_result
  
  - name: get content
    win_shell: 'type C:\output-1.txt'  
    register: content

  - name: write content
    debug:  
      msg: "{{ content.stdout_lines }} "