- name: Report updates for Windows WMs
  hosts: all
  gather_facts: true
  tasks:
  - name: Remove old file, if present
    win_file:
      path: C:\powershell.ps1
      state: absent
    
  - name: Copy a single file
    win_copy:
      src: /tmp/powershell.ps1
      dest: C:\powershell.ps1
    delegate_to: tower-01
  
  - name: Execute a comand in the remote shell, stdout goes to the specified file on the remote
    win_shell: C:\powershell.ps1 >> C:\output-1.txt
    register: script_result
  
  - name: get content
    win_shell: 'type C:\output-1.txt'  
    register: content

  - name: write content
    debug:  
      msg: "{{ content.stdout_lines }} "